//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Core.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailingAddress
    {
        public string MailingAddressID { get; set; }
        public string UserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ParticipantType { get; set; }
        public string ParticipateYouth { get; set; }
        public bool VisaSupport { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string OriginalNationality { get; set; }
        public string CurrentNationality { get; set; }
        public string PassportNumber { get; set; }
        public string TypeOfPassport { get; set; }
        public string Occupation { get; set; }
        public System.DateTime DateOfPassportIssue { get; set; }
        public System.DateTime DateOfPassportExpiry { get; set; }
        public string PassportPhoto1 { get; set; }
        public string PassportPhoto2 { get; set; }
        public string PassportPhoto3 { get; set; }
        public string DetailOfEmbassy { get; set; }
        public bool NeedVisaSupport { get; set; }
        public string ActivationCode { get; set; }
    
        public virtual User User { get; set; }
    }
}
