//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Core.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public string MenuID { get; set; }
        public string Title { get; set; }
        public string ActionURL { get; set; }
        public int DisplayOrder { get; set; }
        public string Language { get; set; }
        public string ParentID { get; set; }
    }
}
