//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Core.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Menu1 = new HashSet<Menu>();
        }
    
        public string MenuID { get; set; }
        public string Title { get; set; }
        public string ActionURL { get; set; }
        public string Language { get; set; }
        public string ParentID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string URL { get; set; }
        public bool Type { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual ICollection<Menu> Menu1 { get; set; }
        public virtual Menu Menu2 { get; set; }
    }
}
