USE [APCRSHR]

GO

ALTER TABLE [Upload] ADD [FilePath] NVARCHAR(200) NULL

GO

DROP TABLE [CONFERENCEDATA]

GO
ALTER TABLE [ConferenceDeclaration] ADD [ActionURL] NVARCHAR(200) NOT NULL

GO

ALTER TABLE [Menu] ADD [Type] BIT NOT NULL DEFAULT(0)

GO

ALTER TABLE [Menu] ADD [URL] NVARCHAR(200) NULL

GO

ALTER TABLE [Menu] ADD [DisplayOrder] INT NOT NULL DEFAULT(0)

GO

ALTER TABLE [Presentation] ADD [ActionURL] NVARCHAR(200) NOT NULL

GO

ALTER TABLE [Photo] ADD [ActionURL] NVARCHAR(200) NOT NULL
GO

ALTER TABLE [Photo] 
ADD FOREIGN KEY (AlbumID) REFERENCES Album(AlbumID)
GO