//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apcrshr_site.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("apcrshr_site.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request.
        /// </summary>
        public static string btn_reset_password {
            get {
                return ResourceManager.GetString("btn_reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update account.
        /// </summary>
        public static string button_editProfile {
            get {
                return ResourceManager.GetString("button_editProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string button_logout {
            get {
                return ResourceManager.GetString("button_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string button_next {
            get {
                return ResourceManager.GetString("button_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string button_previous {
            get {
                return ResourceManager.GetString("button_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string button_register {
            get {
                return ResourceManager.GetString("button_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Change.
        /// </summary>
        public static string button_save {
            get {
                return ResourceManager.GetString("button_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string button_viewProfile {
            get {
                return ResourceManager.GetString("button_viewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string field_confirmPassword_label {
            get {
                return ResourceManager.GetString("field_confirmPassword_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string field_dateOfBirth_label {
            get {
                return ResourceManager.GetString("field_dateOfBirth_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string field_email_label {
            get {
                return ResourceManager.GetString("field_email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string field_fullname_label {
            get {
                return ResourceManager.GetString("field_fullname_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other email address.
        /// </summary>
        public static string field_otherEmail_label {
            get {
                return ResourceManager.GetString("field_otherEmail_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string field_password_label {
            get {
                return ResourceManager.GetString("field_password_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string field_phoneNumber_label {
            get {
                return ResourceManager.GetString("field_phoneNumber_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string field_sex_label {
            get {
                return ResourceManager.GetString("field_sex_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string field_title_label {
            get {
                return ResourceManager.GetString("field_title_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string field_username_label {
            get {
                return ResourceManager.GetString("field_username_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has registered by another user..
        /// </summary>
        public static string msg_email_exist {
            get {
                return ResourceManager.GetString("msg_email_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new password has sent to your registration email..
        /// </summary>
        public static string msg_forgotPassword_emailSend {
            get {
                return ResourceManager.GetString("msg_forgotPassword_emailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid..
        /// </summary>
        public static string msg_invalidEmail {
            get {
                return ResourceManager.GetString("msg_invalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user name has registered by another user..
        /// </summary>
        public static string msg_username_exist {
            get {
                return ResourceManager.GetString("msg_username_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page:.
        /// </summary>
        public static string text_currentPage {
            get {
                return ResourceManager.GetString("text_currentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string text_DoB {
            get {
                return ResourceManager.GetString("text_DoB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string text_email {
            get {
                return ResourceManager.GetString("text_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string text_fullName {
            get {
                return ResourceManager.GetString("text_fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string text_myProfile {
            get {
                return ResourceManager.GetString("text_myProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string text_of {
            get {
                return ResourceManager.GetString("text_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string text_page {
            get {
                return ResourceManager.GetString("text_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input your registration email..
        /// </summary>
        public static string text_reset_password {
            get {
                return ResourceManager.GetString("text_reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string text_sex {
            get {
                return ResourceManager.GetString("text_sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string text_username {
            get {
                return ResourceManager.GetString("text_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album images.
        /// </summary>
        public static string title_albumImage {
            get {
                return ResourceManager.GetString("title_albumImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Presentation.
        /// </summary>
        public static string title_conference {
            get {
                return ResourceManager.GetString("title_conference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Details.
        /// </summary>
        public static string title_conferenceDetail {
            get {
                return ResourceManager.GetString("title_conferenceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline Details.
        /// </summary>
        public static string title_DeadlineDetail {
            get {
                return ResourceManager.GetString("title_DeadlineDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string title_forgotPassword {
            get {
                return ResourceManager.GetString("title_forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Deadlines.
        /// </summary>
        public static string title_importantDeadline {
            get {
                return ResourceManager.GetString("title_importantDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Details.
        /// </summary>
        public static string title_newDetail {
            get {
                return ResourceManager.GetString("title_newDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted by.
        /// </summary>
        public static string title_postedBy {
            get {
                return ResourceManager.GetString("title_postedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation.
        /// </summary>
        public static string title_presentation {
            get {
                return ResourceManager.GetString("title_presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation Details.
        /// </summary>
        public static string title_presentationDetail {
            get {
                return ResourceManager.GetString("title_presentationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Conference.
        /// </summary>
        public static string title_relatedConference {
            get {
                return ResourceManager.GetString("title_relatedConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Deadline.
        /// </summary>
        public static string title_relatedDeadline {
            get {
                return ResourceManager.GetString("title_relatedDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related News.
        /// </summary>
        public static string title_relatedNews {
            get {
                return ResourceManager.GetString("title_relatedNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Presentation.
        /// </summary>
        public static string title_relatedPresentation {
            get {
                return ResourceManager.GetString("title_relatedPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Video.
        /// </summary>
        public static string title_relatedVideo {
            get {
                return ResourceManager.GetString("title_relatedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search resulf.
        /// </summary>
        public static string title_searchResulf {
            get {
                return ResourceManager.GetString("title_searchResulf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string title_video {
            get {
                return ResourceManager.GetString("title_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Details.
        /// </summary>
        public static string title_videoDetails {
            get {
                return ResourceManager.GetString("title_videoDetails", resourceCulture);
            }
        }
    }
}
