//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apcrshr_site.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("apcrshr_site.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update account.
        /// </summary>
        public static string button_editProfile {
            get {
                return ResourceManager.GetString("button_editProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string button_logout {
            get {
                return ResourceManager.GetString("button_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string button_next {
            get {
                return ResourceManager.GetString("button_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string button_previous {
            get {
                return ResourceManager.GetString("button_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string button_viewProfile {
            get {
                return ResourceManager.GetString("button_viewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has registered by another user..
        /// </summary>
        public static string msg_email_exist {
            get {
                return ResourceManager.GetString("msg_email_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has registered by another user..
        /// </summary>
        public static string msg_username_exist {
            get {
                return ResourceManager.GetString("msg_username_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page:.
        /// </summary>
        public static string text_currentPage {
            get {
                return ResourceManager.GetString("text_currentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string text_myProfile {
            get {
                return ResourceManager.GetString("text_myProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string text_of {
            get {
                return ResourceManager.GetString("text_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string text_page {
            get {
                return ResourceManager.GetString("text_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Details.
        /// </summary>
        public static string title_conferenceDetail {
            get {
                return ResourceManager.GetString("title_conferenceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline Details.
        /// </summary>
        public static string title_DeadlineDetail {
            get {
                return ResourceManager.GetString("title_DeadlineDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Details.
        /// </summary>
        public static string title_newDetail {
            get {
                return ResourceManager.GetString("title_newDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted by.
        /// </summary>
        public static string title_postedBy {
            get {
                return ResourceManager.GetString("title_postedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation Details.
        /// </summary>
        public static string title_presentationDetail {
            get {
                return ResourceManager.GetString("title_presentationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Conference.
        /// </summary>
        public static string title_relatedConference {
            get {
                return ResourceManager.GetString("title_relatedConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Deadline.
        /// </summary>
        public static string title_relatedDeadline {
            get {
                return ResourceManager.GetString("title_relatedDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related News.
        /// </summary>
        public static string title_relatedNews {
            get {
                return ResourceManager.GetString("title_relatedNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Presentation.
        /// </summary>
        public static string title_relatedPresentation {
            get {
                return ResourceManager.GetString("title_relatedPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Video.
        /// </summary>
        public static string title_relatedVideo {
            get {
                return ResourceManager.GetString("title_relatedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Details.
        /// </summary>
        public static string title_videoDetails {
            get {
                return ResourceManager.GetString("title_videoDetails", resourceCulture);
            }
        }
    }
}
